spring:
  application:
    name: gulimall-multihub
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    #取消nacos对zipkin的服务发现
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1

server:
  port: 11118